name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install tvscript-tester
        run: pip install ./external/tvscript-tester-0.4.3.tar.gz || echo 'tvtester offline'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          ./.tools/setup_tvtester.sh || echo 'tvtester offline'
      - name: Compile tests
        run: |
          tvscript-tester scripts/AHFT-HPH-v39.0-dev.pine --compile-only --extra-libs library/ahft_utils.pine --symbol BINANCE:BTCUSDT --timeframe 1
          tvscript-tester scripts/AHFT-HPH-v39.0-dev.pine --compile-only --extra-libs library/ahft_utils.pine --symbol BINANCE:BTCUSDT --timeframe 5
          tvscript-tester scripts/AHFT-HPH-v39.0-dev.pine --compile-only --extra-libs library/ahft_utils.pine --symbol BINANCE:BTCUSDT --timeframe 15
        continue-on-error: true
