name: Regression

on:
  push:
    paths: ["scripts/**.pine"]
  pull_request:

jobs:
  pine-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - symbol: BINANCE:BTCUSDT
            tf: "1"
          - symbol: BINANCE:BTCUSDT
            tf: "5"
          - symbol: BINANCE:BTCUSDT
            tf: "15"
          - symbol: BINANCE:SOLUSDT
            tf: "60"
    steps:
      - uses: actions/checkout@v3
      - name: Install tvscript-tester
        run: pip install tvscript-tester
      - name: Run regression
        run: |
          tvscript-tester scripts/AHFT-HPH-v38.8r-4.pine \
            --config configs/baseline_v38.8r-4.pineconfig \
            --symbol ${{ matrix.symbol }} --timeframe ${{ matrix.tf }} \
            --from 2022-01-01 --to 2023-12-31 \
            --assert sharpe>=1.25 max_dd<=0.28 closed_trades>=300
