name: Regression

on:
  push:
    paths: ["scripts/**.pine"]
  pull_request:

jobs:
  pine-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        symbol: [BINANCE:BTCUSDT, BINANCE:ETHUSDT, BINANCE:SOLUSDT]
        tf: ["1","5","15"]
    steps:
      - uses: actions/checkout@v3
      - name: Install tvscript-tester
        run: pip install tvscript-tester==0.4.3
      - name: Compile check
        run: tvscript-tester scripts/AHFT-HPH-v38.9.0-pine.pine --compile-only
      - name: Run regression
        run: |
          tvscript-tester scripts/AHFT-HPH-v38.9.0-pine.pine \
            --config configs/baseline_v38.9.0.pineconfig \
            --symbol ${{ matrix.symbol }} --timeframe ${{ matrix.tf }} \
            --from 2022-01-01 --to 2023-12-31 \
            --assert sharpe>=1.25 max_dd<=0.28 closed_trades>=300
